name: Agent Validation

on:
  push:
    branches:
      - '*'

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Use the version of Python you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run validation
      env: # Or as an environment variable
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LUNARY_APP_ID: ${{ secrets.LUNARY_APP_ID }}
        ACCOUNT_IDENTIFIER: ${{ secrets.ACCOUNT_IDENTIFIER }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        SCHEMA_NAME: ${{ secrets.SCHEMA_NAME }}
        WAREHOUSE_NAME: ${{ secrets.WAREHOUSE_NAME }}
        ROLE_NAME: ${{ secrets.ROLE_NAME }}
      run: python validation.py
